### ISSUE TITLE
Agility Helper: Delay picking up marks at Ardy

### ISSUE THREAD

**Issue by justanotherGHuser** [Ganom/Supporter-Issue-Tracker#13]
**Is your feature request related to a problem? Please describe.**
Currently every time a mark spawns on the Ardy rooftops, the plugin will always pick it up before moving on, thus slowing the xp/h down.

**Describe the solution you'd like**
Have a variable to set when the plugin will pick them up (every X laps or every X minutes)

**Describe alternatives you've considered**

**Additional context**

**Comment by Ganom** [comment]
Picking them up only costs you 1 tick, but every pick up takes 1 tick, so wouldn't this be a 0 sum change? Unless shown otherwise i'm going to mark this as a wont-fix.

**Comment by Failed4life** [comment]
On the Ardy Course, Marks of Grace always spawn in the same spot - and do not despawn unless you get logged out. The idea behind @legobrickrs suggestion is to let the Marks stack up and loot them as a stack, rather than as soon as 1 is available. This would technically save ticks in the long run and theoretically increase xp/hr, depending on how many are stacked before looting them.
I understand the suggestion, but it isn't _really_ necessary. If it was implemented, I'd say an option to loot on "x" stack, rather than "x" laps or "x" minutes. - This would only be applied to the Ardy course though, as other courses do not behave in the same manner.

e.g Looting a stack of 10 marks would save 9 game ticks, since you looted them all at once
